# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TableEffect(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TableEffect()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTableEffect(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TableEffect
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TableEffect
    def Datalist(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from TableEffectRowData import TableEffectRowData
            obj = TableEffectRowData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TableEffect
    def DatalistLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # TableEffect
    def DatalistIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def TableEffectStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddDatalist(builder, datalist): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(datalist), 0)
def TableEffectAddDatalist(builder, datalist):
    """This method is deprecated. Please switch to AddDatalist."""
    return AddDatalist(builder, datalist)
def StartDatalistVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TableEffectStartDatalistVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartDatalistVector(builder, numElems)
def End(builder): return builder.EndObject()
def TableEffectEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)